# Copyright 2024 Robert Bosch GmbH
#
# SPDX-License-Identifier: Apache-2.0

default: install


.PHONY: install
install:
	npm install


.PHONY: clean
clean:
	rm -rf package-lock.json
	rm -rf node_modules

.PHONY: cleanall
cleanall: clean
